/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICreditScore,
  ICreditScoreInterface,
} from "../../SimpleLending.sol/ICreditScore";

const _abi = [
  {
    type: "function",
    name: "getScore",
    inputs: [
      {
        name: "user",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class ICreditScore__factory {
  static readonly abi = _abi;
  static createInterface(): ICreditScoreInterface {
    return new utils.Interface(_abi) as ICreditScoreInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICreditScore {
    return new Contract(address, _abi, signerOrProvider) as ICreditScore;
  }
}
