/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICreditScore__factory } from "./ICreditScore__factory";
export { SimpleLending__factory } from "./SimpleLending__factory";
