/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as simpleLendingSol from "./SimpleLending.sol";
export { CreditScore__factory } from "./CreditScore__factory";
