/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as simpleLendingSol from "./SimpleLending.sol";
export type { simpleLendingSol };
export type { CreditScore } from "./CreditScore";
export * as factories from "./factories";
export { CreditScore__factory } from "./factories/CreditScore__factory";
export type { SimpleLending } from "./SimpleLending.sol/SimpleLending";
export { SimpleLending__factory } from "./factories/SimpleLending.sol/SimpleLending__factory";
export type { ICreditScore } from "./SimpleLending.sol/ICreditScore";
export { ICreditScore__factory } from "./factories/SimpleLending.sol/ICreditScore__factory";
